version: "2"
services:
  postgres:
    image: postgres:10-alpine
    restart: unless-stopped
    networks:
      - default
    volumes:
     - /opt/matrix/pgdata:/var/lib/postgresql/data
    environment:
     - POSTGRES_PASSWORD=Pass4now!
     - POSTGRES_USER=synapse
     - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    labels:
      - "traefik.enable=false"
      
  sygnal:
    image: matrixdotorg/sygnal:v0.2.4
    restart: unless-stopped
    networks: 
      - web
      - default
    environment: 
      - SYGNAL_CONF=/etc/sygnal/sygnal.conf
    volumes:
      - /opt/matrix/sygnal:/etc/sygnal

  synapse:
    image: avhost/docker-matrix:v1.0.0
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - web
      - default
    ports:
     # Coturn
     - "3478:3478"
     - "5349:5349"
    volumes:
     - /opt/matrix/synapse:/data
     - /docker-volumes/etc/letsencrypt/live/dev-matrix.seavus.com/fullchain.pem:/data/fullchain.pem
     - /docker-volumes/etc/letsencrypt/live/dev-matrix.seavus.com/privkey.pem:/data/privkey.pem
    labels:
      - "traefik.backend=synapse"
      - "traefik.enable=true"
      - "traefik.frontend=true"
      - "traefik.port=8008"
      - "traefik.frontend.rule=Host:dev-matrix.seavus.com"
      - "traefik.docker.network=web"
  nginx:
    image: nginx:1.12-alpine
    restart: unless-stopped
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:dev-matrix.seavus.com"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.port=80"
      - "traefik.docker.network=web"
    volumes:
      - ./nginx/matrix.conf:/etc/nginx/conf.d/matrix.conf
      - ./nginx/www:/var/www/
      - /docker-volumes/etc/letsencrypt/live/dev-matrix.seavus.com/fullchain.pem:/etc/letsencrypt/live/dev-matrix.seavus.com/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/dev-matrix.seavus.com/privkey.pem:/etc/letsencrypt/live/dev-matrix.seavus.com/privkey.pem
networks:
  default:
    external:
      name: matrix
  # Traefiks network
  web:
    external: true















